// components
export { default as MainLayout } from './templates/MainLayout/MainLayout'
export { default as ManagementLayout } from './templates/ManagementLayout'
export { default as Header } from './templates/Header/Header'
export { default as Sidebar } from './SideBar/SideBar'
export { default as Outlets } from './pages/Dashboard/Outlets'
export { default as FormSearch } from './pages/Kasir/Head/FormSearch'
export { default as Pagination } from './templates/Pagination'
export { default as TripleButtons } from './templates/TripleButtons'
export { default as NoData } from './templates/NoData'
export { default as FormGroup } from './templates/FormGroup'
export { default as Modal } from './templates/Modal'
export { default as Loading } from './templates/Loading'
export { default as Locked } from './templates/Locked'
export { default as Notification } from './templates/Notification'

// pages
export { default as Dashboard } from './pages/Dashboard/Dashboard'
export { default as Kasir } from './pages/Kasir/Kasir'
export { default as Produk } from './pages/Produk/Produk'
export { default as Satuan } from './pages/Satuan/Satuan'
export { default as Kategori } from './pages/Kategori/Kategori'
export { default as Pelanggan } from './pages/Pelanggan/Pelanggan'
export { default as Supplier } from './pages/Supplier/Supplier'
export { default as Cabang } from './pages/Cabang'
export { default as RiwayatTransaksi } from './pages/RiwayatTransaksi'
export { default as Pembelian } from './pages/Pembelian'
export { default as Akun } from './pages/Akun'
export { default as Tutorial } from './pages/Tutorial/Tutorial'
export { default as Upgrade } from './pages/Upgrade/Upgrade'
export { default as Landing } from './pages/Landing'
export { default as NotFound } from './pages/NotFound'